<?php

namespace ProjectPunchclock\PunchclockBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PunchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PunchRepository extends EntityRepository
{
}