<?php

namespace ProjectPunchclock\PunchclockBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PunchDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PunchDetailRepository extends EntityRepository
{
}
